name: Deploy Multilingual Site

on:  
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Загрузка репозитория в в рабочую среду GitHub Actions
        uses: actions/checkout@v4
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.REP_TOKEN }}
          publish_dir: ./sites
          keep_files: true
