name: Deploy Multilingual Site

on:  
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code #Загрузка репозитория в в рабочую среду GitHub Actions
        uses: actions/checkout@v4

      - name: Create version directory
        run: |
          site_version=$(echo ${{ github.ref }} | cut -d/ -f2) #извлечение имени релиза
          mkdir -p ./sites/versions/v${site_version}/ru/
          mkdir -p ./sites/versions/v${site_version}/en/ 
           mkdir -p ./sites/versions/
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.REP_TOKEN }}
          publish_dir: ./sites
          target_branch: gh-pages-v${{ github.ref }} 
          keep_files: true
